"""empty message

Revision ID: fe83e06e6bcd
Revises: 2e2993b4acf4
Create Date: 2021-01-22 19:56:54.218047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe83e06e6bcd'
down_revision = '2e2993b4acf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'user_id')
    # ### end Alembic commands ###
